### ISSUE TITLE
v3.0.0 does not support bun(x) - npm & pnpm are working.

### ISSUE THREAD

**Issue by LarsArtmann** [rse/upd#9]
# upd v3.0.0 does not support bun(x) - for main logic

## Description

The `upd` version 3.0.0 throws a TypeError when executed with `bunx`, while it works correctly with `npm` and `pnpm`.

## Environment

- **upd version**: 3.0.0
- **bun version**: 1.2.11
- **Working package managers**: npm (10.9.2), pnpm (10.10.0)
- **Failing package manager**: bun

## Error Details

When running `bunx upd`, the following error occurs:

```
ERROR: TypeError: ansiRegex is not a function
    at module.exports (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/node_modules/strip-ansi/index.js:4:72)
    at stringWidth (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/index.js:11:11)
    at /Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:12:12
    at Array.reduce (<anonymous>)
    at Object.strlen (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:11:16)
    at Cell.mergeTableOptions (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/cell.js:71:31)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:54:14)
    at Array.forEach (<anonymous>)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:53:11)
    at Array.forEach (<anonymous>)
```

## Steps to Reproduce

1. Install bun (if not already installed)
2. Run `bunx upd -V` (works, shows version)
3. Run `bunx upd` (fails with TypeError)

## Expected Behavior

`upd` should execute successfully with bun, similar to how it works with npm and pnpm.

## Actual Behavior

The tool crashes with a TypeError related to `ansiRegex` not being a function in the dependency chain through `cli-table3`.

## Workarounds

Use `npx upd` or `pnpx upd` instead of `bunx upd`.

## Additional Information

- The issue appears to be in the dependency chain: `cli-table3` → `string-width` → `strip-ansi`
- The error suggests a module resolution or compatibility issue specific to bun's module system
- Previous versions of upd were not tested with bun, so it's unclear if this is a regression

## Successful Output (with npm/pnpm)

When using npm or pnpm, the tool works correctly and shows:

```
┌────────────────────────────────────┬──────────────┬──────────────┬─────────┐
│ MODULE NAME                        │ VERSION OLD  │ VERSION NEW  │ STATE   │
│ @typespec/prettier-plugin-typespec │ 0.63.0       │ 1.0.0        │ updated │
│ @typespec/compiler                 │ 0.63.0       │ 1.0.0        │ updated │
│ @typespec/http                     │ 0.63.0       │ 1.0.1        │ updated │
│ @typespec/json-schema              │ 0.63.0       │ 1.0.0        │ updated │
│ @typespec/openapi3                 │ 0.63.0       │ 1.0.0        │ updated │
│ @typespec/rest                     │ 0.63.0       │ 0.70.0       │ updated │
└────────────────────────────────────┴──────────────┴──────────────┴─────────┘
```

**Comment by rse** [comment]
Hmmmm.. unfortunately, at least under macOS with latest Bun 1.2.13 I cannot repeat this problem:

```
$ git clone ssh://github.com/rse/upd
Cloning into 'upd'...
remote: Enumerating objects: 999, done.
remote: Counting objects: 100% (247/247), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 999 (delta 159), reused 238 (delta 150), pack-reused 752 (from 1)
Receiving objects: 100% (999/999), 228.01 KiB | 796.00 KiB/s, done.
Resolving deltas: 100% (658/658), done.
rse@en4:/Users/rse/Work/bun
$ cd upd/
rse@en4:/Users/rse/Work/bun/upd
$ bun i
bun install v1.2.13 (64ed68c9)

+ @eslint/js@9.28.0
+ eslint@9.28.0
+ eslint-plugin-import@2.31.0
+ eslint-plugin-n@17.19.0
+ eslint-plugin-promise@7.2.1
+ globals@16.2.0
+ neostandard@0.12.1
+ awaity@1.0.0
+ chalk@5.4.1
+ cli-table3@0.6.5
+ ducky@2.8.2
+ escape-string-regexp@5.0.0
+ fast-diff@1.3.0
+ json-asty@1.2.3
+ micromatch@4.0.8
+ pacote@21.0.0
+ pretty-bytes@7.0.0
+ progress@2.0.3
+ semver@7.7.2
+ strip-ansi@7.1.0
+ update-notifier@7.3.1
+ yargs@18.0.0

580 packages installed [246.00ms]

Blocked 2 postinstalls. Run `bun pm untrusted` for details.
rse@en4:/Users/rse/Work/bun/upd
$ bun upd.js 
┌─────────────────────────────────────────────────────────────────────────────┐
│                     ALL PACKAGE DEPENDENCIES UP-TO-DATE                     │
└─────────────────────────────────────────────────────────────────────────────┘
rse@en4:/Users/rse/Work/bun/upd
$ bunx upd
┌─────────────────────────────────────────────────────────────────────────────┐
│                     ALL PACKAGE DEPENDENCIES UP-TO-DATE                     │
└─────────────────────────────────────────────────────────────────────────────┘
rse@en4:/Users/rse/Work/bun/upd
$ bun --version
1.2.13
rse@en4:/Users/rse/Work/bun/upd
$ 
```

**Comment by LarsArtmann** [comment]
I worked on MacOS 15.5 (24F74) + bun version `1.2.11` + upd version `2.9.8` BUT not in version `3.0.0`.

```txt
➜ git:(master) ✗ bunx upd -V
upd 2.9.8 <http://github.com/rse/upd>
Upgrade NPM Package Dependencies
Copyright (c) 2015-2024 Dr. Ralf S. Engelschall <http://engelschall.com>
Licensed under MIT <http://spdx.org/licenses/MIT.html>

➜ git:(master) ✗ bunx upd (version 2.9.8)
Works :)

➜  SwettySwipper git:(master) ✗ bun add upd
bun add v1.2.11 (cb6abd21)

...

installed upd@3.0.0 with binaries:
 - upd

212 packages installed [6.73s]
➜ git:(master) ✗ upd -V
upd 3.0.0 <http://github.com/rse/upd>
Upgrade NPM Package Dependencies
Copyright (c) 2015-2025 Dr. Ralf S. Engelschall <http://engelschall.com>
Licensed under MIT <http://spdx.org/licenses/MIT.html>

➜  SwettySwipper git:(master) ✗ upd (version 3.0.0)
ERROR: TypeError: ansiRegex is not a function
    at module.exports (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/node_modules/strip-ansi/index.js:4:72)
    at stringWidth (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/index.js:11:11)
    at /Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:12:12
    at Array.reduce (<anonymous>)
    at Object.strlen (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:11:16)
    at Cell.mergeTableOptions (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/cell.js:71:31)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:54:14)
    at Array.forEach (<anonymous>)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:53:11)
    at Table.forEach (<anonymous>)
```

**Comment by LarsArtmann** [comment]
**I am closing this issue for inconsistency/non-reproducible.**


My results on the same machine:

```sh
➜  event-store git:(master) ✗ upd -V
upd 3.0.0 <http://github.com/rse/upd>
Upgrade NPM Package Dependencies
Copyright (c) 2015-2025 Dr. Ralf S. Engelschall <http://engelschall.com>
Licensed under MIT <http://spdx.org/licenses/MIT.html>

➜  event-store git:(master) ✗ upd
checking:  14% 0.0s 144kB: nanoid         
checking:  42% 0.0s 207kB: @sinonjs/fake-tichecking:  
checking:  57% 0.0s 304kB: @libsql/client
checking:  85% 0.2s 1.26MB: @castore/core  
checking:  100% 0.3s 9.32MB: typescript

ERROR: TypeError: ansiRegex is not a function
    at module.exports (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/node_modules/strip-ansi/index.js:4:72)
    at stringWidth (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/node_modules/string-width/index.js:11:11)
    at /Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:12:12
    at Array.reduce (<anonymous>)
    at Object.strlen (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/utils.js:11:16)
    at Cell.mergeTableOptions (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/cell.js:71:31)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:54:14)
    at Array.forEach (<anonymous>)
    at Table.<anonymous> (/Users/larsartmann/.bun/install/global/node_modules/cli-table3/src/table.js:53:11)
    at Array.forEach (<anonymous>)
````

```sh
➜  event-store git:(master) ✗ bunx upd -V
upd 3.0.0 <http://github.com/rse/upd>
Upgrade NPM Package Dependencies
Copyright (c) 2015-2025 Dr. Ralf S. Engelschall <http://engelschall.com>
Licensed under MIT <http://spdx.org/licenses/MIT.html>

➜  event-store git:(master) ✗ bunx upd
checking:  14% 0.0s 96.9kB: @libsql/client 
checking:  42% 0.0s 253kB: @types/sinonjs__
checking:  71% 0.1s 1.21MB: zod            
checking:  85% 0.4s 9.26MB: typescript     
checking:  100% 0.5s 9.32MB: @sinonjs/fake-
┌─────────────────────────────────────┬──────────────┬──────────────┬─────────┐
│ MODULE NAME                         │ VERSION OLD  │ VERSION NEW  │ STATE   │
│ typescript                          │ 5.6.2        │ 5.8.3        │ updated │
│ @libsql/client                      │ 0.6.0        │ 0.15.8       │ updated │
│ nanoid                              │ 5.0.7        │ 5.1.5        │ updated │
│ zod                                 │ 3.23.8       │ 3.25.56      │ updated │
└─────────────────────────────────────┴──────────────┴──────────────┴─────────┘

```
